### PR TITLE
Charles branch

### PR DESCRIPTION
**Pull request by cpontier**
Here's where I've gotten. I think this base file will give us a good place to branch out. Let me know if you'd like to get going.

### CODE REVIEW

**Review by hmlanden — CHANGES_REQUESTED** [review]
renaming the columns must be inplace=True

**Comment by hmlanden** [comment]
For Urban/Rural, do we know which is which for column values? Column values are 1 or 2

**Comment by hmlanden** [comment]
Also, do you think we should drop the year column? Since we already know that we're doing 2014, might just save us a bit of mem space while doing work

**Review by pdoshi95 — APPROVED** [review]

**Review by dollyye — APPROVED** [review]

**Comment by hmlanden** [comment]
@cpontier can you make the change I mentioned and merge to master? :D

**Comment by cpontier** [comment]
Sorry about that. Hope to get it this afternoon.

**Pull request merged**
